services:
  pol-ler:
    platform: linux/amd64
    build:
      context: .
    environment:
      DB_NAME: 'politepol'
      DB_USER: 'poluser'
      DB_PASSWORD: 'polpassword'
      DB_HOST: 'db-pol-ler'
      DB_PORT: '5432'
      WEB_PORT: '8088'
      TIME_ZONE: 'America/Fortaleza'
    image: pol-ler:latest
    depends_on:
      db-pol-ler:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-pol-ler", "/bin/bash", "./frontend/start.sh"]
    container_name: pol-ler
    restart: unless-stopped
    networks:
      - pol-ler-network
    ports:
      - '8088:8088'

  db-pol-ler:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: db-pol-ler
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'politepol'
      POSTGRES_USER: 'poluser'
      POSTGRES_PASSWORD: 'polpassword'
    networks:
      - pol-ler-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poluser -d politepol"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  pol-ler-network:
    driver: 'bridge'
